name: Proposal Label add to Issue
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
        with:
          project: Open Mic Conference - ScalaMatsuri 2023
          column: Proposal
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
