name: Issue assign to Project
on:
  issues:
    types:
      - opened
env:
  GITHUB_TOKEN: ${{ secrets.SCALAMATSURI_2023_OPEN_MIC_CONFERENCE_ACTIONS }}
jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
      - name: Project に割り当てる
        uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project: 'https://github.com/orgs/scalamatsuri/projects/12'
          column_name: 'Proposal'
